### ISSUE TITLE
Mozilla RTCPeerConnection error

### ISSUE THREAD

**Issue by okpatil4u** [alongubkin/phonertc#114]
With mozilla browser, I am having following error
Error: RTCPeerConnection constructor passed invalid RTCConfiguration - missing credential: turn:ec2-54-68-238-149.us-west-2.compute.amazonaws.com:3478

**Comment by BurhanBozkurt** [comment]
@okpatil4u I am getting the same error. Did you find the reason for that?
Thank you.

**Comment by alongubkin** [comment]
@BurhanBozkurt This is the TURN server of the demo. That server is not active anymore. You should setup your own server, as described in the documentation.

**Comment by BurhanBozkurt** [comment]
@alongubkin Thank you for your reply but I am getting this error on my own TURN server. The problem is with Mozilla Firefox only. Works fine with Chrome though. Any thoughts?
May be it is related to a specific TURN configuration. Below is the start log of my TURN server.

root@server1 [/etc]# turnserver --ne=2
0: log file opened: /var/log/turn_14028_2016-02-08.log
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Citrix-3.2.5.9 'Marshal West'
0: 
Max number of open files/sockets allowed for this process: 4096
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 2000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: Redis is not supported
0: PostgreSQL is not supported
0: MySQL supported
0: OpenSSL compile-time version 0x1000105f: fresh enough
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Config file found: /etc/turnserver.conf
0: Listener address to use: *my server external ip address*
0: Config file found: /etc/turnserver.conf
0: Config file found: /etc/turnuserdb.conf
0: WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: Relay address to use: *my server external ip address*
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay *my server external ip address* initialization...
0:   relay *my server external ip address* initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=2 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=3 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=4 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=5 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=6 created
0: IO method (udp listener/relay thread): epoll (with changelist)
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=7 created
0: turn server id=128 created
0: Total UDP servers: 1
0: Total General servers: 8
0: IO method (auth thread): epoll (with changelist)
0: IO method (cli thread): epoll (with changelist)

**Comment by alongubkin** [comment]
Try to test your TURN server without PhoneRTC to see if it works
